// Renders tests/support/ids.ts from the catalogue, so a test-case or bug id that does not exist is a compile
// error (OI-4). JSON imports widen to `string`, hence a generated file with literal unions.
export function renderIds(caseIds: string[], bugIds: string[]): string {
  const list = (ids: string[]) => ids.map((id) => `  '${id}',`).join('\n');
  return `// GENERATED by scripts/gen-ids.mjs from spec/test-cases.json and spec/bugs.json. Do not edit by hand.
export const TC_IDS = [
${list([...caseIds].sort())}
] as const;
export type TcId = (typeof TC_IDS)[number];

export const BUG_IDS = [
${list([...bugIds].sort())}
] as const;
export type BugId = (typeof BUG_IDS)[number];
`;
}
