// Which test cases exercise each documented operation. TC-META-02 fails when /docs/json lists an operation missing here.
export const OPERATION_MAP: Record<string, string[]> = {
  'GET /api/health': ['TC-META-01'],
  'GET /robots.txt': ['TC-META-03'],
  'GET /api/config': ['TC-META-03'],
  'POST /api/auth/register': ['TC-REG-01', 'TC-REG-02', 'TC-REG-03', 'TC-REG-04', 'TC-REG-05', 'TC-REG-06', 'TC-REG-07', 'TC-REG-08', 'TC-REG-09'],
  'POST /api/auth/login': ['TC-AUTH-01', 'TC-AUTH-02'],
  'POST /api/auth/logout': ['TC-AUTH-04'],
  'GET /api/auth/me': ['TC-AUTH-01', 'TC-AUTH-04'],
  'GET /api/events': ['TC-EVT-01', 'TC-EVT-04', 'TC-EVT-05', 'TC-EVT-06', 'TC-EVT-07', 'TC-EVT-08', 'TC-EVT-09', 'TC-EVT-10', 'TC-EVT-11', 'TC-EVT-12', 'TC-EVT-13'],
  'POST /api/events': ['TC-ADM-03'],
  'GET /api/events/{id}': ['TC-EVT-02', 'TC-EVT-03'],
  'PUT /api/events/{id}': ['TC-ADM-04'],
  'DELETE /api/events/{id}': ['TC-ADM-05'],
  'GET /api/cart': ['TC-CART-02', 'TC-CART-03', 'TC-CART-08'],
  'POST /api/cart/items': ['TC-CART-01', 'TC-CART-02', 'TC-CART-03', 'TC-CART-04', 'TC-CART-05', 'TC-CART-06', 'TC-VIP-01', 'TC-VIP-02', 'TC-VIP-03', 'TC-VIP-04'],
  'PATCH /api/cart/items/{id}': ['TC-CART-07', 'TC-VIP-05', 'TC-ORD-05'],
  'POST /api/cart/discount': ['TC-DISC-01', 'TC-DISC-02', 'TC-DISC-03', 'TC-DISC-04', 'TC-DISC-05', 'TC-DISC-06', 'TC-DISC-07', 'TC-DISC-09', 'TC-DISC-10', 'TC-DISC-11'],
  'POST /api/orders': ['TC-CHK-01', 'TC-CHK-02', 'TC-CHK-03', 'TC-CHK-04', 'TC-CHK-05', 'TC-CHK-06', 'TC-CHK-07', 'TC-CHK-08', 'TC-CHK-09', 'TC-CHK-10', 'TC-CHK-11', 'TC-VIP-06', 'TC-DISC-08'],
  'GET /api/orders': ['TC-ORD-01'],
  'GET /api/orders/{id}': ['TC-ORD-02', 'TC-ORD-03'],
  'POST /api/orders/{id}/cancel': ['TC-CAN-01', 'TC-CAN-02', 'TC-CAN-03', 'TC-CAN-05', 'TC-ORD-04'],
  'GET /api/profile': ['TC-PROF-01'],
  'PATCH /api/profile': ['TC-PROF-01', 'TC-PROF-02', 'TC-PROF-03'],
  'POST /api/profile/password': ['TC-PROF-04', 'TC-PROF-05', 'TC-PROF-06', 'TC-PROF-07'],
  'PATCH /api/ticket-types/{id}': ['TC-ADM-06'],
  'GET /api/admin/orders': ['TC-ADM-01', 'TC-ADM-08'],
  'DELETE /api/admin/orders/{id}': ['TC-ADM-07', 'TC-ADM-08'],
  'GET /api/admin/orders.csv': ['TC-ADM-02', 'TC-ADM-08'],
};
